# Copyright (C) 2022, Gauthier Leonard
# See the file LICENSE for licensing terms.
---
- name: Create the blockchains
  hosts: subnet_control_node
  vars_prompt:
    - name: control_password
      prompt: Subnet control password
  tasks:
    - name: Create the blockchains
      include_role:
        name: nuttymoon.avalanche.blockchain
      vars:
        subnet_control_username: subnav_admin
        subnet_control_password: "{{ control_password }}"
        blockchain_vm: "{{ blockchain.vm }}"
        blockchain_name: "{{ blockchain.name }}"
        blockchain_aliases: "{{ blockchain.aliases }}"
        blockchain_genesis_params: "{{ blockchain.genesis_params }}"
      loop: "{{ create_blockchains }}"
      loop_control:
        loop_var: blockchain
