# Copyright (C) 2022, Gauthier Leonard
# See the file LICENSE for licensing terms.
---
- name: Create the subnet
  hosts: subnet_control_node
  vars_prompt:
    - name: control_password
      prompt: Subnet control password
  roles:
    - role: nuttymoon.avalanche.subnet
      vars:
        subnet_control_username: subnav_admin
        subnet_control_password: "{{ control_password }}"
